apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: issuetest
  namespace: jira
spec:
  template:
    spec:
      containers:
      - image: github.com/savitaashture/simple-go-app 
