apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: envApp
spec:
  template:
    spec:
      containers:
      - image: github.com/savitaashture/simple-go-app
        env:
        - name: TARGET
          value: "v1"
